package lexertoken

type TokenType int

const (
	TOKEN_ERROR TokenType = iota
	TOKEN_EOF

	TOKEN_PACKAGE
	TOKEN_MODULE
	TOKEN_INTERFACE
	TOKEN_IMPORT
	TOKEN_INCLUDE
	TOKEN_CLASS
	TOKEN_FUNCTION
	TOKEN_TASK
	TOKEN_SUPERCLASS
	TOKEN_TYPE
	TOKEN_VARIABLE
	TOKEN_LEFT_PAREN
	TOKEN_RIGHT_PAREN
	TOKEN_METHOD_CALL
	TOKEN_DEFINED_VALUE
	TOKEN_CONDITIONAL_DEF
	TOKEN_LEFT_BRACKET
	TOKEN_RIGHT_BRACKET
	TOKEN_NEWLINE
	TOKEN_IFDEF
	TOKEN_IFNDEF
	TOKEN_DEFINE
	TOKEN_ENDIFDEF
	TOKEN_ELSE
	TOKEN_ELSIF
	TOKEN_SEMICOLON

	// Operators
	TOKEN_EQUAL_SIGN
	TOKEN_BLOCKING_ASSIGNMENT
)
